name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Extract Zip File
      run: |
        unzip -o untitled.zip

    - name: Build APK with Gradle
      run: |
        GRADLE_FILE=$(find . -maxdepth 3 -name "gradlew" | head -n 1)
        PROJECT_DIR=$(dirname "$GRADLE_FILE")
        cd "$PROJECT_DIR"
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: '**/build/outputs/apk/debug/*.apk'
